name: Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to build"
        required: true
        default: "android"
        type: choice
        options:
          - android
          - ios
      profile:
        description: "EAS build profile"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - preview
          - production

jobs:
  lint-typescript-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack (Yarn Berry)
        run: corepack enable

      - name: Use Yarn v4.9.4
        run: corepack prepare yarn@4.9.4 --activate
      
      - name: Check Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Verify Expo configuration
        run: npx expo-doctor

      - name: Run TypeScript check
        run: yarn tsc --noEmit

      - name: Run ESLint
        run: yarn eslint . --ext .ts,.tsx

      - name: Run Prettier
        run: yarn prettier --check .

  eas-build:
    runs-on: ubuntu-latest
    needs: lint-typescript-prettier
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Verify EAS CLI availability
        run: yarn dlx eas-cli@latest --version

      - name: Run EAS build
        run: yarn dlx eas-cli@latest build --platform ${{ github.event.inputs.platform }} --profile ${{ github.event.inputs.profile }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
