name: CI

on:
  pull_request:
    types: [opened, reopened]
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: corepack enable

      - uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - run: yarn install --immutable

      - run: yarn tsc --noEmit

      - run: yarn eslint . --ext .ts,.tsx
